//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobBoard.DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public int ApplicationId { get; set; }
        public int OpenPositionId { get; set; }
        public string UserId { get; set; }
        public System.DateTime ApplicationDate { get; set; }
        public string ManagerNotes { get; set; }
        public int ApplicationStatus { get; set; }
        public string ResumeFilename { get; set; }
    
        public virtual ApplicationStatus ApplicationStatu { get; set; }
        public virtual OpenPositions OpenPosition { get; set; }
        public virtual UserDetails UserDetail { get; set; }
    }
}
